{ pkgs, lib, config, ... }:

let
  stable = import <nixos-stable/nixpkgs> { config = config.nixpkgs.config; };
in
{
  environment.systemPackages = with pkgs; [
    floorp
    libusb
    libsForQt5.qtwayland
    xorg.libxcb
    xorg.xcbutil
    xorg.xcbproto
    cudaPackages.cudatoolkit
    cudaPackages.cuda_cudart
    cudaPackages.cudnn
    cudaPackages.libcublas
    cudaPackages.cutensor
    libsForQt5.full
    libsForQt5.qt5.qtx11extras
    distrobox
    cmake
    (pkgs.python3.override {
      bluezSupport = true;
    })
    android-tools
    grim
    slurp
    wl-clipboard
    mako
    gnumake
    libvlc
    onlyoffice-bin_latest
    nodejs
    wineWowPackages.staging
    winetricks
    libgcc
    gcc
    ffmpeg
    mono
    nodePackages.pnpm
    conda
    acl
    temurin-bin
    temurin-bin-8
    temurin-bin-17
    haxe
    neko
    hashlink
    nh
    tk
    egl-wayland
    looking-glass-client
    git
    unzip
    cdrkit
    fuse3
    openssl
    pkg-config
    vital
    carla
    rustup
    ryujinx
    linuxHeaders
    python310
    yabridge
    yabridgectl
  ];
}
